name: Build & Deploy App

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Debug server secrets
      - name: Debug server secrets
        run: |
          if [ -z "${{ secrets.SERVER_SSH_KEY }}" ]; then
            echo "❌ SERVER_SSH_KEY is missing"
            exit 1
          fi
          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
            echo "❌ SERVER_HOST is missing"
            exit 1
          fi
          if [ -z "${{ secrets.SERVER_USER }}" ]; then
            echo "❌ SERVER_USER is missing"
            exit 1
          fi
          echo "✅ All server secrets are set"

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build backend JAR
      - name: Build backend JAR
        working-directory: server-side/task-service
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # Check GHCR token
      - name: Check GHCR token
        run: |
          if [ -z "${{ vars.PTIT_GITHUB_TOKEN }}" ]; then
            echo "❌ PTIT_GITHUB_TOKEN is NOT set!"
            exit 1
          else
            echo "✅ PTIT_GITHUB_TOKEN is set"
          fi

      # Login to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dodt1306
          password: ${{ vars.PTIT_GITHUB_TOKEN }}

      # Build & Push backend
      - name: Build & Push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server-side/task-service
          file: ./server-side/task-service/Dockerfile
          push: true
          tags: ghcr.io/dodt1306/to-do-list-app:latest
          platforms: linux/arm64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Build & Push frontend
      - name: Build & Push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./client-side
          file: ./client-side/Dockerfile
          push: true
          tags: ghcr.io/dodt1306/to-do-list-frontend:latest
          platforms: linux/arm64

      # Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo /home/deploy/deploy.sh
